### ISSUE TITLE
409 Error at boot

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut-mobile#28] opened 2015-08-17 20:56 UTC
Application does not load.

To recreate, clear all previous data associated with site in browser, then go to url.

409 error:

    null
    bundle.js:17 CustomPouchError {status: 409, name: "conflict", message: "Document update conflict", error: true}
    bundle.js:17 ^^^^^ Error updating designDoc for questions:
    bundle.js:17 Object {_id: "_design/questions", views: Object}

**Comment by mikeymckay** [comment] 2015-08-18 21:37
Yikes. Ok. How are you clearing data? I guess I need to check for this state then force pouchdb to reset the database also.

**Comment by fetmar** [comment] 2015-08-19 17:50
The first time I went or in any subsequent new browser I tried had the same error. I thought I did something wrong so I tried again but I wanted to clear everything out first.

I only know how to do it in chrome and that's the one I did repeated tests with. 

Chrome settings | show advanced settings | under "privacy" Content Data | All Cookies and Site Data

Then you can search for whatever site you want and delete everything for it.

**Comment by mikeymckay** [comment] 2015-08-25 18:29
Closed Duplicate of #56

**Closed by mikeymckay** 2015-08-25 18:29 UTC
Labels: bug
