### ISSUE TITLE
New Visit form saved automatically as incomplete

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-mobile#59] opened 2015-08-25 13:35 UTC
Not sure if this is meant to function this way. I noticed that if I click the + to add a new visit, and without entering any data, I click to view the results, the new visit form is already added to the incomplete forms in the results. This causes unintended blank forms being saved as incomplete.

**Comment by gmcressman** [comment] 2015-08-25 17:07
Duplicate of #52

**Comment by scloo** [comment] 2015-08-25 18:11
This issue is somewhat different from #52, where a new incomplete visit is created when you click Complete. For this case, merely clicking the + icon saves the visit as incomplete. And if I press the Back button on the tablet, when the 'new' form is displayed on the screen, even though there seems to be no activity (nothing change on the screen), each time I press the Back button, it creates a new incomplete visit in the background

**Comment by gmcressman** [comment] 2015-08-25 18:16
I believe this is the same issue as #52, with the same root cause. I'll let you and Mike decide.

**Comment by mikeymckay** [comment] 2015-08-25 18:42
This the same issue. For each question on the form you can have a property called "action_on_questions_loaded". I use this to preset the patient ID and to mark the Hospital Referral checkbox to no. As soon as the questions loads, this code gets executed and the values set. The page views this as an update to the record, so it saves it, which updates the URL. Pressing back then return to the empty record URL, which then loads the questions and creates another new record. 

        {
         "id": "883",
          "_id": "883",
          "label": "Patient ID",
          "type": "text",
          "repeatable": "false",
          "validation": "console.log \"|#{value}|\";if not value.match(/^[A-Za-z][0-9]$/) then \"Value must be an upper case letter followed by a number\"",
          "required": "true",
          "action_on_change": "$('#883').val($('#883').val().toUpperCase())",
          "action_on_questions_loaded": "$('#883').attr('maxLength','2');  Coconut.database.query 'results', {startkey:['Visit',true,{}],endkey:['Visit',true],limit:1,descending:true,include_docs:true}, (error,result) => if result.rows.length is 1 then $('#883').val(result.rows[0].doc.PatientID) and $('#883').parent().addClass('is-dirty'); $('#883').attr('onkeyup','this.value = this.value.toUpperCase()')"
        },


    {
      "id": "1230",
      "_id": "1230",
      "label": "Transferred to Hospital",
      "type": "radio",
      "repeatable": "false",
      "radio-options": "Yes, No",
      "validation": "",
      "required": "true",
      "safeLabel": "Gender",
      "action_on_questions_loaded": "if not ResultOfQuestion('TransferredtoHospital')? then $('input[name=TransferredtoHospital]').filter('[value=No]').click()"

**Closed by mikeymckay** 2015-08-25 18:42 UTC
