### ISSUE TITLE
Split up ID into two fields

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut-mobile#30] opened 2015-08-18 03:50 UTC
Id should consist of two fields and validate accordingly.

The first field should be 2 alphabetic characters, the second field should be 3 numeric characters.

The first two characters should have recent entries listed as autofill suggestions.

**Comment by gmcressman** [comment] 2015-08-18 12:15
Duplicate of #29

**Closed** 2015-08-18 21:36 UTC
Labels: enhancement
